[project]
name = "kaggling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=0.3.10",
    "pandas>=2.2.3",
]
